#-------------------------------------------------------------------------------
# Note for using the rate-limiting:
#   The comment part won't be copied if you use the subgenerator docker-compose
#   you have to manually copy it
#-------------------------------------------------------------------------------
version: '2'
services:
    gatway-app:
        image: gatway
        external_links:
            - gatway-mongodb:mongodb
            # Uncomment to have Cassandra working with the gateway
            # - gatway-cassandra:cassandra
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017
            - SPRING_DATA_MONGODB_DATABASE=gatway
            - SPRING_DATA_CASSANDRA_CONTACTPOINTS=cassandra
            - JHIPSTER_SLEEP=30 # gives time for the Cassandra cluster to start and execute the migration scripts
        ports:
            - 8080:8080
    gatway-mongodb:
        extends:
            file: mongodb.yml
            service: gatway-mongodb
    # Uncomment to have Cassandra working with the gateway
    # gatway-cassandra:
    #     extends:
    #         file: cassandra-cluster.yml
    #         service: gatway-cassandra
    # gatway-cassandra-migration:
    #     extends:
    #         file: cassandra-migration.yml
    #         service: gatway-cassandra-migration
    #     environment:
    #         - CREATE_KEYSPACE_SCRIPT=create-keyspace-prod.cql
