version: '2'
services:
    gatway-mongodb:
        container_name: gatway-mongodb
        image: mongo:3.2.10
        ports:
            - "27017:27017"
        # volumes:
        #     - ~/volumes/jhipster/gatway/mongodb/:/data/db/
