version: '2'
services:
    catalog-app:
        image: catalog
        external_links:
            - catalog-mongodb:mongodb
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017
            - SPRING_DATA_MONGODB_DATABASE=catalog
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
    catalog-mongodb:
        extends:
            file: mongodb.yml
            service: catalog-mongodb
